---
name: e2e test

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  getexamples:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    runs-on: ubuntu-latest
    outputs:
      examples: ${{ steps.getexamples.outputs.examples }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 #v4.1.6
      - name: get examples
        id: getexamples
        uses: Azure/terraform-azurerm-avm-template/.github/actions/e2e-getexamples@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  testexamples:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    runs-on: ubuntu-latest # self-hosted, 1ES.Pool=terraform-azurerm-avm-template
    needs: getexamples
    environment: test
    env:
      TF_IN_AUTOMATION: 1
      TF_VAR_enable_telemetry: false
    strategy:
      matrix:
        example: ${{ fromJson(needs.getexamples.outputs.examples) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 #v4.1.6
      
      - name: Log into Azure
        uses: azure/login@v1
        with:
         auth-type: IDENTITY
         client-id: ${{  secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{  secrets.AZURE_TENANT_ID }}
         subscription-id: ${{  secrets.AZURE_SUBSCRIPTION_ID }}
    
      - name: Test example
        shell: bash
        run: |

          export ARM_SUBSCRIPTION_ID= ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          export ARM_TENANT_ID= ${{ secrets.AZURE_TENANT_ID }}
          export ARM_CLIENT_ID= ${{ secrets.AZURE_CLIENT_ID }}
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src -w /src --network=host -e TF_IN_AUTOMATION -e TF_VAR_enable_telemetry -e AVM_MOD_PATH=/src -e AVM_EXAMPLE=${{ matrix.example }} -e MSI_ID -e ARM_SUBSCRIPTION_ID -e ARM_TENANT_ID -e ARM_CLIENT_ID -e ARM_USE_MSI=true mcr.microsoft.com/azterraform:latest make test-example

  # This job is only run when all the previous jobs are successful.
  # We can use it for PR validation to ensure all examples have completed.
  testexamplescomplete:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    runs-on: ubuntu-latest
    needs: testexamples
    steps:
      - run: echo "All tests passed"
